# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Sahbi Haj Belgacem
email:            sahbi21@gmail.com
tagline:          'A Personal Jekyll Blog'
description:      Hey my name is Sahbi. I'm currently studying MIS @Hes-so in Switzerland.
url:              http://sa7bi.github.io
baseurl:          /

author:
  name:           'Sahbi Haj Belgacem'
  url:            https://twitter.com/sa7bi

paginate:         5

# Social
version:          2.1.0
social:
  github:           https://github.com/sa7bi
  twitter:          https://twitter.com/sa7bi
  facebook:         https://facebook.com/sahbi           
